# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Julian\Documents\Studium\Projekt_Multimedia\PSE-WS1718\GUI-alternativ\advanced.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(211, 401)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setWindowTitle("Erweiterte Optionen")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 191, 111))
        self.groupBox.setTitle("Farb-Thresholds")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label.setText("Hue-Threshold")
        self.label.setObjectName("label")
        self.spin_hue = QtWidgets.QSpinBox(self.groupBox)
        self.spin_hue.setGeometry(QtCore.QRect(140, 20, 42, 22))
        self.spin_hue.setMaximum(360)
        self.spin_hue.setProperty("value", 30)
        self.spin_hue.setObjectName("spin_hue")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 111, 16))
        self.label_2.setText("Saturation-Threshold")
        self.label_2.setObjectName("label_2")
        self.spin_sat = QtWidgets.QSpinBox(self.groupBox)
        self.spin_sat.setGeometry(QtCore.QRect(140, 50, 42, 22))
        self.spin_sat.setMaximum(255)
        self.spin_sat.setProperty("value", 60)
        self.spin_sat.setObjectName("spin_sat")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 101, 16))
        self.label_3.setText("Value-Threshold")
        self.label_3.setObjectName("label_3")
        self.spin_val = QtWidgets.QSpinBox(self.groupBox)
        self.spin_val.setGeometry(QtCore.QRect(140, 80, 42, 22))
        self.spin_val.setMaximum(255)
        self.spin_val.setProperty("value", 180)
        self.spin_val.setObjectName("spin_val")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 300, 191, 61))
        self.groupBox_3.setTitle("Sonstiges")
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_shiftInBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_shiftInBox.setGeometry(QtCore.QRect(10, 20, 171, 31))
        self.checkBox_shiftInBox.setText("Farben innerhalb der gesamten\nHitbox verändern")
        self.checkBox_shiftInBox.setObjectName("checkBox_shiftInBox")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 130, 191, 71))
        self.groupBox_2.setTitle("Feathering")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label_4.setText("Federradius um Maske")
        self.label_4.setObjectName("label_4")
        self.slider_feather = QtWidgets.QSlider(self.groupBox_2)
        self.slider_feather.setGeometry(QtCore.QRect(10, 40, 171, 22))
        self.slider_feather.setMaximum(80)
        self.slider_feather.setProperty("value", 10)
        self.slider_feather.setOrientation(QtCore.Qt.Horizontal)
        self.slider_feather.setObjectName("slider_feather")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(140, 20, 41, 16))
        self.label_5.setText("10")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(130, 370, 75, 23))
        self.pushButton.setText("Ok")
        self.pushButton.setObjectName("pushButton")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 210, 191, 80))
        self.groupBox_4.setTitle("Gruppierung")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_6.setText("Cluster")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_7.setText("Precision")
        self.label_7.setObjectName("label_7")
        self.spin_cluster = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_cluster.setGeometry(QtCore.QRect(140, 20, 42, 22))
        self.spin_cluster.setMinimum(2)
        self.spin_cluster.setMaximum(10)
        self.spin_cluster.setProperty("value", 4)
        self.spin_cluster.setObjectName("spin_cluster")
        self.spin_precision = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_precision.setGeometry(QtCore.QRect(140, 50, 42, 22))
        self.spin_precision.setMinimum(1)
        self.spin_precision.setMaximum(8)
        self.spin_precision.setProperty("value", 3)
        self.spin_precision.setObjectName("spin_precision")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.close)
        self.spin_hue.valueChanged['int'].connect(Dialog.set_threshold_hue)
        self.spin_sat.valueChanged['int'].connect(Dialog.set_threshold_sat)
        self.spin_val.valueChanged['int'].connect(Dialog.set_threshold_val)
        self.spin_cluster.valueChanged['int'].connect(Dialog.set_cluster_size)
        self.spin_precision.valueChanged['int'].connect(Dialog.set_group_precision)
        self.slider_feather.valueChanged['int'].connect(self.label_5.setNum)
        self.slider_feather.valueChanged['int'].connect(Dialog.set_feather_radius)
        self.checkBox_shiftInBox.toggled['bool'].connect(Dialog.set_shift_hitbox)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        pass