# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Julian\Documents\Studium\Projekt_Multimedia\PSE-WS1718\GUI-alternativ\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(900, 560)
        mainWindow.setMinimumSize(QtCore.QSize(900, 560))
        mainWindow.setWindowTitle("Verarbeiten")
        mainWindow.setWindowOpacity(1.0)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imagesLayout = QtWidgets.QHBoxLayout()
        self.imagesLayout.setObjectName("imagesLayout")
        self.origImgLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.origImgLabel.sizePolicy().hasHeightForWidth())
        self.origImgLabel.setSizePolicy(sizePolicy)
        self.origImgLabel.setToolTip("Originalbild")
        self.origImgLabel.setStatusTip("")
        self.origImgLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.origImgLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.origImgLabel.setText("")
        self.origImgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.origImgLabel.setObjectName("origImgLabel")
        self.imagesLayout.addWidget(self.origImgLabel)
        self.resultImgLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultImgLabel.sizePolicy().hasHeightForWidth())
        self.resultImgLabel.setSizePolicy(sizePolicy)
        self.resultImgLabel.setToolTip("Verarbeitetes Bild")
        self.resultImgLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.resultImgLabel.setText("")
        self.resultImgLabel.setObjectName("resultImgLabel")
        self.resultImgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imagesLayout.addWidget(self.resultImgLabel)
        self.verticalLayout_2.addLayout(self.imagesLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
#        self.btnSelectFrame = QtWidgets.QPushButton(self.centralwidget)
#        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
#        sizePolicy.setHorizontalStretch(0)
#        sizePolicy.setVerticalStretch(0)
#        sizePolicy.setHeightForWidth(self.btnSelectFrame.sizePolicy().hasHeightForWidth())
#        self.btnSelectFrame.setSizePolicy(sizePolicy)
#        self.btnSelectFrame.setMinimumSize(QtCore.QSize(150, 0))
#        self.btnSelectFrame.setText("Anderen Frame auswählen")
#        self.btnSelectFrame.setObjectName("btnSelectFrame")
#        self.horizontalLayout_9.addWidget(self.btnSelectFrame)
#        self.currentFrameLabel = QtWidgets.QLabel(self.centralwidget)
#        self.currentFrameLabel.setText("Aktueller Frame: 0")
#        self.currentFrameLabel.setObjectName("currentFrameLabel")
#        self.horizontalLayout_9.addWidget(self.currentFrameLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 216))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 216))
        self.groupBox.setTitle("Kleiderfarbenveränderung")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.colorsListView = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorsListView.sizePolicy().hasHeightForWidth())
        self.colorsListView.setSizePolicy(sizePolicy)
        self.colorsListView.setMinimumSize(QtCore.QSize(0, 150))
        self.colorsListView.setMaximumSize(QtCore.QSize(16777215, 150))
        self.colorsListView.setObjectName("colorsListView")
        self.verticalLayout.addWidget(self.colorsListView)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnAddColor = QtWidgets.QPushButton(self.groupBox)
        self.btnAddColor.setText("Farbe Hinzufügen")
        self.btnAddColor.setObjectName("btnAddColor")
        self.horizontalLayout_5.addWidget(self.btnAddColor)
        self.btnRemoveColor = QtWidgets.QPushButton(self.groupBox)
        self.btnRemoveColor.setText("Farbe Entfernen")
        self.btnRemoveColor.setObjectName("btnRemoveColor")
        self.horizontalLayout_5.addWidget(self.btnRemoveColor)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.colorSelect_currentColor = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorSelect_currentColor.sizePolicy().hasHeightForWidth())
        self.colorSelect_currentColor.setSizePolicy(sizePolicy)
        self.colorSelect_currentColor.setText("")
        self.colorSelect_currentColor.setObjectName("colorSelect_currentColor")
        self.colorSelect_currentColor.setEnabled(False)
        self.horizontalLayout_6.addWidget(self.colorSelect_currentColor)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setText("Aktuelle Farbe der Kleidung")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setText("Ändern zu")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(18)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.destHue_color = QtWidgets.QRadioButton(self.groupBox)
        self.destHue_color.setText("Farbe")
        self.destHue_color.setChecked(True)
        self.destHue_color.setObjectName("destHue_color")
        self.horizontalLayout_7.addWidget(self.destHue_color)
        self.destHue_rainbow = QtWidgets.QRadioButton(self.groupBox)
        self.destHue_rainbow.setText("Farbwechsel")
        self.destHue_rainbow.setObjectName("destHue_rainbow")
        self.horizontalLayout_7.addWidget(self.destHue_rainbow)
        self.destHue_strobe = QtWidgets.QRadioButton(self.groupBox)
        self.destHue_strobe.setText("Buntes Blinken")
        self.destHue_strobe.setObjectName("destHue_strobe")
        self.horizontalLayout_7.addWidget(self.destHue_strobe)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.destColorWrap = QtWidgets.QHBoxLayout()
        self.destColorWrap.setObjectName("destColorWrap")
        self.colorSelect_destColor = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorSelect_destColor.sizePolicy().hasHeightForWidth())
        self.colorSelect_destColor.setSizePolicy(sizePolicy)
        self.colorSelect_destColor.setText("")
        self.colorSelect_destColor.setObjectName("colorSelect_destColor")
        self.colorSelect_destColor.setEnabled(False)
        self.destColorWrap.addWidget(self.colorSelect_destColor)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setText("Zielfarbe der Kleidung")
        self.label_4.setObjectName("label_4")
        self.destColorWrap.addWidget(self.label_4)
        self.verticalLayout_5.addLayout(self.destColorWrap)
        self.destSpeedWrap = QtWidgets.QVBoxLayout()
        self.destSpeedWrap.setObjectName("destSpeedWrap")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setText("Geschwindigkeit")
        self.label_5.setObjectName("label_5")
        self.destSpeedWrap.addWidget(self.label_5)
        self.colorchangeSpeedSlider = QtWidgets.QSlider(self.groupBox)
        self.colorchangeSpeedSlider.setMaximum(80)
        self.colorchangeSpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.colorchangeSpeedSlider.setObjectName("colorchangeSpeedSlider")
        self.colorchangeSpeedSlider.setSliderPosition(5)
        self.destSpeedWrap.addWidget(self.colorchangeSpeedSlider)
        self.verticalLayout_5.addLayout(self.destSpeedWrap)
        self.label_5.setVisible(False)
        self.colorchangeSpeedSlider.setVisible(False)
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 127))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 104))
        self.groupBox_2.setTitle("Personenerkennung")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_showMasks = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_showMasks.sizePolicy().hasHeightForWidth())
        self.checkBox_showMasks.setSizePolicy(sizePolicy)
        self.checkBox_showMasks.setText("Erkannte Personenumrisse markieren")
        self.checkBox_showMasks.setObjectName("checkBox_showMasks")
        self.verticalLayout_4.addWidget(self.checkBox_showMasks)
        self.checkBox_showHitboxes = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_showHitboxes.setText("Rahmen um erkannte Personen zeichnen")
        self.checkBox_showHitboxes.setObjectName("checkBox_showHitboxes")
        self.verticalLayout_4.addWidget(self.checkBox_showHitboxes)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.colorSelect_mask = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorSelect_mask.sizePolicy().hasHeightForWidth())
        self.colorSelect_mask.setSizePolicy(sizePolicy)
        self.colorSelect_mask.setStyleSheet("")
        self.colorSelect_mask.setText("")
        self.colorSelect_mask.setCheckable(False)
        self.colorSelect_mask.setDefault(False)
        self.colorSelect_mask.setFlat(False)
        self.colorSelect_mask.setObjectName("colorSelect_mask")
        self.horizontalLayout.addWidget(self.colorSelect_mask)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("Markier- und Rahmenfarbe")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.checkBox_groupMasks = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_groupMasks.setText("Masken gruppieren")
        self.checkBox_groupMasks.setObjectName("checkBox_groupMasks")
        self.verticalLayout_4.addWidget(self.checkBox_groupMasks)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 29, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
#        self.btnAdvanced = QtWidgets.QPushButton(self.centralwidget)
#        self.btnAdvanced.setText("Erweiterte Optionen")
#        self.btnAdvanced.setObjectName("btnAdvanced")
#        self.verticalLayout_3.addWidget(self.btnAdvanced)
        
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnProcess = QtWidgets.QPushButton(self.centralwidget)
        self.btnProcess.setText("Verarbeiten")
        self.btnProcess.setObjectName("btnProcess")
        self.horizontalLayout_10.addWidget(self.btnProcess)
        self.btnAdvanced = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdvanced.setText("Erweitert ...")
        self.btnAdvanced.setObjectName("btnAdvanced")
        self.horizontalLayout_10.addWidget(self.btnAdvanced)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setText("Schließen")
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_4.addWidget(self.btnClose)
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setText("Speichern ...")
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_4.addWidget(self.btnSave)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        self.statusProgressBar = QtWidgets.QProgressBar()
        self.statusProgressBar.hide()
        self.statusbar.addPermanentWidget(self.statusProgressBar)
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
#        self.btnSelectFrame.clicked.connect(mainWindow.selectNewFrame)
        self.btnAddColor.clicked.connect(mainWindow.add_color)
        self.btnRemoveColor.clicked.connect(mainWindow.remove_color)
        self.btnProcess.clicked.connect(mainWindow.process_data)
        self.btnAdvanced.clicked.connect(mainWindow.show_advanced_options)
        self.btnClose.clicked.connect(mainWindow.close)
        self.btnSave.clicked.connect(mainWindow.save_file)
        self.checkBox_showMasks.toggled['bool'].connect(mainWindow.set_show_masks)
        self.checkBox_showHitboxes.toggled['bool'].connect(mainWindow.set_show_box)
        self.checkBox_groupMasks.toggled['bool'].connect(mainWindow.set_group_masks)
        self.colorsListView.clicked['QModelIndex'].connect(mainWindow.color_option_selected)
        self.destHue_color.clicked.connect(mainWindow.set_target_solid_color)
        self.destHue_rainbow.clicked.connect(mainWindow.set_target_rainbow)
        self.destHue_strobe.clicked.connect(mainWindow.set_target_flash)
        self.colorSelect_currentColor.clicked.connect(mainWindow.set_color_current)
        self.colorSelect_destColor.clicked.connect(mainWindow.set_color_target)
        self.colorSelect_mask.clicked.connect(mainWindow.set_color_overlay)
        self.colorchangeSpeedSlider.valueChanged['int'].connect(mainWindow.change_color_speed)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        pass